#drop schema company;
create schema company;
use company;

CREATE TABLE COM_DEPARTMENT 
    ( 
     DEPARTMENT_NO      VARCHAR (20)  NOT NULL , 
     DEPARTMENT_NAME    VARCHAR (30) , 
     MANAGER_START_DATE VARCHAR (8) , 
     EMPLOYEE_ID        VARCHAR (50)  NOT NULL 
    ) 
;

ALTER TABLE COM_DEPARTMENT 
    ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY ( DEPARTMENT_NO ) ;

CREATE TABLE COM_DEPARTMENT_LOCATION 
    ( 
     LOCATION_NO   VARCHAR (20)  NOT NULL , 
     LOCATION_NAME VARCHAR (50) , 
     DEPARTMENT_NO VARCHAR (20)  NOT NULL 
    ) 
;

ALTER TABLE COM_DEPARTMENT_LOCATION 
    ADD CONSTRAINT DEPARTMENT_LOCATION_PK PRIMARY KEY ( LOCATION_NO ) ;

CREATE TABLE COM_EMPLOYEE 
    ( 
     EMPLOYEE_ID   VARCHAR (50)  NOT NULL , 
     NAME          VARCHAR (30) , 
     SSN           VARCHAR (15) , 
     ADDRESS       VARCHAR (500) , 
     SALARY        DECIMAL (14,2) , 
     GENDER        CHAR (1) , 
     BIRTH_DATE    VARCHAR (8) , 
     DEPARTMENT_NO VARCHAR (20)  NOT NULL , 
     EMPLOYEE_ID1  VARCHAR (50)  NOT NULL 
    ) 
;

ALTER TABLE COM_EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY ( EMPLOYEE_ID ) ;

CREATE TABLE COM_PROJECT 
    ( 
     PROJECT_NAME  VARCHAR (50) , 
     PROJECT_NO    VARCHAR (50)  NOT NULL , 
     프로젝트수행장소      VARCHAR (500) , 
     DEPARTMENT_NO VARCHAR (20)  NOT NULL 
    ) 
;

ALTER TABLE COM_PROJECT 
    ADD CONSTRAINT PROJECT_PK PRIMARY KEY ( PROJECT_NO ) ;

CREATE TABLE COM_WORK_PROJECT 
    ( 
     EMPLOYEE_ID      VARCHAR (50)  NOT NULL , 
     WORK_DAYS_AMOUNT INT , 
     PROJECT_NO       VARCHAR (50)  NOT NULL 
    ) 
;

ALTER TABLE COM_WORK_PROJECT 
    ADD CONSTRAINT WORK_PROJECT_PK PRIMARY KEY ( EMPLOYEE_ID, PROJECT_NO ) ;

ALTER TABLE COM_PROJECT 
    ADD CONSTRAINT DEPARTMENT_FK FOREIGN KEY 
    ( 
     DEPARTMENT_NO
    ) 
    REFERENCES COM_DEPARTMENT 
    ( 
     DEPARTMENT_NO
    ) 
;

ALTER TABLE COM_DEPARTMENT_LOCATION 
    ADD CONSTRAINT DEPARTMENT_FKv1 FOREIGN KEY 
    ( 
     DEPARTMENT_NO
    ) 
    REFERENCES COM_DEPARTMENT 
    ( 
     DEPARTMENT_NO
    ) 
;

ALTER TABLE COM_EMPLOYEE 
    ADD CONSTRAINT DEPARTMENT_FKv2 FOREIGN KEY 
    ( 
     DEPARTMENT_NO
    ) 
    REFERENCES COM_DEPARTMENT 
    ( 
     DEPARTMENT_NO
    ) 
;

ALTER TABLE COM_DEPARTMENT 
    ADD CONSTRAINT EMPLOYEE_FK FOREIGN KEY 
    ( 
     EMPLOYEE_ID
    ) 
    REFERENCES COM_EMPLOYEE 
    ( 
     EMPLOYEE_ID
    ) 
;

ALTER TABLE COM_EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_FKv1 FOREIGN KEY 
    ( 
     EMPLOYEE_ID1
    ) 
    REFERENCES COM_EMPLOYEE 
    ( 
     EMPLOYEE_ID
    ) 
;

ALTER TABLE COM_WORK_PROJECT 
    ADD CONSTRAINT EMPLOYEE_FKv2 FOREIGN KEY 
    ( 
     EMPLOYEE_ID
    ) 
    REFERENCES COM_EMPLOYEE 
    ( 
     EMPLOYEE_ID
    ) 
;

ALTER TABLE COM_WORK_PROJECT 
    ADD CONSTRAINT PROJECT_FK FOREIGN KEY 
    ( 
     PROJECT_NO
    ) 
    REFERENCES COM_PROJECT 
    ( 
     PROJECT_NO
    ) 
;


