#drop SCHEMA  if exists company;

CREATE SCHEMA if exists company;

use company;

CREATE TABLE DEPARTMENT 
    ( 
     DEPARTMENT_NO      varchar (20)  NOT NULL , 
     DEPARTMENT_NAME    varchar (30) , 
     MANAGER_START_DATE varchar (8) , 
     EMPLOYEE_ID        varchar (50)  NOT NULL 
    ) 
;

ALTER TABLE DEPARTMENT 
    ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY ( DEPARTMENT_NO ) ;

CREATE TABLE DEPARTMENT_LOCATION 
    ( 
     LOCATION_NO   varchar (20)  NOT NULL , 
     LOCATION_NAME varchar (50) , 
     DEPARTMENT_NO varchar (20)  NOT NULL 
    ) 
;

ALTER TABLE DEPARTMENT_LOCATION 
    ADD CONSTRAINT DEPARTMENT_LOCATION_PK PRIMARY KEY ( LOCATION_NO ) ;

CREATE TABLE EMPLOYEE 
    ( 
     EMPLOYEE_ID   varchar (50)  NOT NULL , 
     NAME          varchar (30) , 
     SSN           varchar (15) , 
     ADDRESS       varchar (500) , 
     SALARY        decimal(14,2) , 
     GENDER        CHAR (1) , 
     BIRTH_DATE    varchar (8) , 
     DEPARTMENT_NO varchar (20)  NOT NULL , 
     EMPLOYEE_ID   varchar (50)  NOT NULL 
    ) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY ( EMPLOYEE_ID ) ;

CREATE TABLE PROJECT 
    ( 
     PROJECT_NO       varchar (50)  NOT NULL , 
     PROJECT_NAME     varchar (50) , 
     PROJECT_LOCATION varchar (500) , 
     DEPARTMENT_NO    varchar (20)  NOT NULL 
    ) 
;

ALTER TABLE PROJECT 
    ADD CONSTRAINT PROJECT_PK PRIMARY KEY ( PROJECT_NO ) ;

CREATE TABLE WORK_PROJECT 
    ( 
     EMPLOYEE_ID      varchar (50)  NOT NULL , 
     PROJECT_NO       varchar (50)  NOT NULL , 
     WORK_DAYS_AMOUNT INTEGER 
    ) 
;

ALTER TABLE WORK_PROJECT 
    ADD CONSTRAINT WORK_PROJECT_PK PRIMARY KEY ( EMPLOYEE_ID, PROJECT_NO ) ;

ALTER TABLE PROJECT 
    ADD CONSTRAINT COM_DEPARTMENT_FK FOREIGN KEY 
    ( 
     DEPARTMENT_NO
    ) 
    REFERENCES DEPARTMENT 
    ( 
     DEPARTMENT_NO
    ) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT COM_DEPARTMENT_FKv1 FOREIGN KEY 
    ( 
     DEPARTMENT_NO
    ) 
    REFERENCES DEPARTMENT 
    ( 
     DEPARTMENT_NO
    ) 
;

ALTER TABLE DEPARTMENT_LOCATION 
    ADD CONSTRAINT COM_DEPARTMENT_FKv2 FOREIGN KEY 
    ( 
     DEPARTMENT_NO
    ) 
    REFERENCES DEPARTMENT 
    ( 
     DEPARTMENT_NO
    ) 
;

ALTER TABLE DEPARTMENT 
    ADD CONSTRAINT COM_EMPLOYEE_FK FOREIGN KEY 
    ( 
     EMPLOYEE_ID
    ) 
    REFERENCES EMPLOYEE 
    ( 
     EMPLOYEE_ID
    ) 
;

ALTER TABLE EMPLOYEE 
    ADD CONSTRAINT COM_EMPLOYEE_FKv1 FOREIGN KEY 
    ( 
     EMPLOYEE_ID
    ) 
    REFERENCES EMPLOYEE 
    ( 
     EMPLOYEE_ID
    ) 
;

ALTER TABLE WORK_PROJECT 
    ADD CONSTRAINT COM_EMPLOYEE_FKv2 FOREIGN KEY 
    ( 
     EMPLOYEE_ID
    ) 
    REFERENCES EMPLOYEE 
    ( 
     EMPLOYEE_ID
    ) 
;

ALTER TABLE WORK_PROJECT 
    ADD CONSTRAINT COM_PROJECT_FK FOREIGN KEY 
    ( 
     PROJECT_NO
    ) 
    REFERENCES PROJECT 
    ( 
     PROJECT_NO
    ) 
;